// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAit9WA2CvZy5lKDBgsgGqTo_y20p9qFMk',
    appId: '1:440746809317:web:5ab21dea94c5d51f8fc10c',
    messagingSenderId: '440746809317',
    projectId: 'laza-3d8f3',
    authDomain: 'laza-3d8f3.firebaseapp.com',
    storageBucket: 'laza-3d8f3.firebasestorage.app',
    measurementId: 'G-PW8BMZS64N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_DSjPObmDjI4BFrDytlMH5kmoSj49TTI',
    appId: '1:440746809317:android:953aa49f41e0b4ea8fc10c',
    messagingSenderId: '440746809317',
    projectId: 'laza-3d8f3',
    storageBucket: 'laza-3d8f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ITOTY7GGc7BMZVTcnt2FNN0WS_JVrhs',
    appId: '1:440746809317:ios:26f5e38795890f2e8fc10c',
    messagingSenderId: '440746809317',
    projectId: 'laza-3d8f3',
    storageBucket: 'laza-3d8f3.firebasestorage.app',
    iosBundleId: 'com.example.laza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ITOTY7GGc7BMZVTcnt2FNN0WS_JVrhs',
    appId: '1:440746809317:ios:26f5e38795890f2e8fc10c',
    messagingSenderId: '440746809317',
    projectId: 'laza-3d8f3',
    storageBucket: 'laza-3d8f3.firebasestorage.app',
    iosBundleId: 'com.example.laza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAit9WA2CvZy5lKDBgsgGqTo_y20p9qFMk',
    appId: '1:440746809317:web:597d4803fd24b1c58fc10c',
    messagingSenderId: '440746809317',
    projectId: 'laza-3d8f3',
    authDomain: 'laza-3d8f3.firebaseapp.com',
    storageBucket: 'laza-3d8f3.firebasestorage.app',
    measurementId: 'G-RKHM88TRP7',
  );
}
